WIP - Do not merge
Vonage/vonage-php-sdk-core pull request #257
Opened 2020-10-07 08:36 UTC by SoftCreatR

* #257 Dropped support for PHPUnit 7
* #257 Added missing PHPDoc blocks
* #257 Added missing return type hints
* #257 Replaced qualifiers with imports
* #257 Updated and optimized examples
* #257 Applied multiple code optimizations (especially for PHP 7.2+) and simplified some logic
* #257 Updated code styling to match PSR standards
* #257 Re-ordered imports where necessary
* #257 Updated tests to get rid of deprecation messages
* #257 Updated phpunit.xml.dist
* #257 Added Roave Security Advisories as dev-requirement to prevent usage of packages with known security vulnerabilities
* #257 Removed test build for PHP 7.1 in .travis.yml
* #257 Added missing punctuation in CONTRIBUTING.md
* #257 Updated contact email address in CODE_OF_CONDUCT.md

* #257 Fixed namespaces (Zend => Laminas, Nexmo => Vonage)
* #257 Fixed typos and some wording in README.md

## Description

## Motivation and Context

## How Has This Been Tested?

## Example Output or Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-13 22:39 UTC, SoftCreatR commented
@Lczajkowski I'm still not done 😄

2020-10-14 04:04 UTC, SoftCreatR commented
Finally 🚀 🔥 🥳 🎉

2020-10-14 16:37 UTC, dragonmantank commented on composer.json
> +  "homepage": "https://www.vonage.com",
I would set this to `https://developer.nexmo.com` so that it points people directly to the docs

2020-10-14 16:37 UTC, SoftCreatR commented on .travis.yml
>  language: php
I've just refactored what's there and this file exists in your repo. But sure,i can just delete it.

2020-10-14 16:39 UTC, SoftCreatR commented on composer.json
> +  "homepage": "https://www.vonage.com",
But that's not the purpose of this field. For this, there's a field called `support` and there, the docs are linked.

2020-10-14 17:00 UTC, dragonmantank requested changes
Did a quick spot check for some high-level items, so this is not a comprehensive review. 

Overall looks really good, but have some questions and some reverts and changes I would like to see done (mainly based on the why we did some things why we did).

I will have more as I chunk this up and dig through.

2020-10-14 17:01 UTC, dragonmantank commented on composer.json
> +  "homepage": "https://www.vonage.com",
We consider it the homepage for our APIs though, even though it's not the company homepage.

2020-10-14 17:02 UTC, dragonmantank commented on .travis.yml
>  language: php
Totally understand! We switched to Github Actions and never deleted this file in case we needed to switch back, but GHA has been working fine. I just hadn't gotten around to deleting it myself :P

2020-10-14 17:03 UTC, dragonmantank commented
Marking this accepted ... there's a lot of good changes in here so thanks for doing a lot of this work! Just want to make sure you get both Hacktoberfest and Vonage credit for the work in case we don't merge it in time

2020-10-14 17:03 UTC, SoftCreatR commented on src/Account/ClientFactory.php
> +            ->setBaseUri('/account');
> Does that cause a conflict with one of the rulesets?

Not really. But most IDEs will probably remove it.

2020-10-14 17:05 UTC, SoftCreatR commented on src/Account/Price.php
> +        return [];
Wouldn't `mixed` fit better? Feels like cheating, but works as expected.

2020-10-14 17:06 UTC, SoftCreatR commented on src/Application/Application.php
> +            if (isset($data['rtc']['webhooks'])) {
That's not true for `empty` :)

2020-10-14 17:09 UTC, SoftCreatR commented on src/Application/Application.php
> +            if (isset($data['rtc']['webhooks'])) {
http://sandbox.onlinephpfunctions.com/code/3b7370c9c80919e4e7fe1313f7ac9a12879d9b58

2020-10-14 17:09 UTC, SoftCreatR commented on src/Application/Application.php
> +            if (isset($capabilities['voice']['webhooks'])) {
http://sandbox.onlinephpfunctions.com/code/3b7370c9c80919e4e7fe1313f7ac9a12879d9b58

2020-10-14 17:16 UTC, dragonmantank commented on src/Account/Price.php
> +        return [];
`mixed` would be a good return docblock value since we don't really know what the return value is, and will cover `null`.

A lot of the array access code is being nuked in v3, so this just avoids a BC break. If we start returning `[]` instead of `null` we have the possibility of messing up a developer's checks.

2020-10-14 17:21 UTC, SoftCreatR commented on src/Account/Price.php
> +        return [];
Well, `mixed` wouldn't fit. Instead, I'll hint it as `array|null`, since $data is (and was) annotated as an array (which is, why i returned an empty array instead of `null`).

2020-10-14 17:21 UTC, dragonmantank commented on src/Application/Application.php
> +            if (isset($capabilities['voice']['webhooks'])) {
I stand corrected!

Though if you do see any `and` conditionals please swap them to `&&` for consistency

2020-10-14 17:22 UTC, SoftCreatR commented on src/Application/Application.php
> +            if (isset($capabilities['voice']['webhooks'])) {
That's what I've done, where needed ;)

2020-10-14 17:35 UTC, SoftCreatR commented on src/Account/ClientFactory.php
> +            ->setBaseUri('/account');
I would leave this for now, since there are many places where method chaining is used, and my IDE keeps trimming those lines.

2020-10-14 19:08 UTC, dragonmantank requested changes
Handful of other cleanup items, currently about 75 files total into the PR :P

2020-10-14 19:08 UTC, dragonmantank commented on src/Account/Config.php
> +     * @param null $sms_callback_url
I would set all these to `string|null`

2020-10-14 20:23 UTC, SoftCreatR commented on src/Call/Talk.php
> +        if (!in_array($offset, $this->params, false)) {
Old habits, I guess.

2020-10-14 20:27 UTC, SoftCreatR commented on src/Client/ClientAwareTrait.php
> +        throw new RuntimeException('Vonage\Client not set');
But it was there already?

2020-10-14 20:30 UTC, SoftCreatR commented on src/Call/Talk.php
> +     * @return mixed
Must be `string|null` then :)

2020-10-14 20:33 UTC, dragonmantank requested changes
Handful of new changes

2020-10-14 20:33 UTC, dragonmantank commented on src/Client.php
> +            'message' => Message\Client::class,
For consistency, I would either revert this or rename them all the `[X]Client` via the `use ... as [X]Client`

2020-10-14 20:33 UTC, dragonmantank commented on src/Client.php
> -                function (
While we don't use these parameters, I would keep them so they match the PHP docs

2020-10-14 20:33 UTC, dragonmantank commented on src/Client.php
> +     * @return \GuzzleHttp\Client|HttpClient
This could just be `ClientInterface` now, since we now support PSR-18 directly versus our wrapper we used to have

2020-10-14 20:33 UTC, dragonmantank commented on src/Client.php
> +                $c = $this->credentials->get(Keypair::class)->generateJwt();
I would rename `$c` -> `$token` for clarity, since we're getting a JWT out of this call.

2020-10-14 20:33 UTC, dragonmantank commented on src/Client.php
> +            $c = $this->credentials->generateJwt();
Same here, `$c` -> `$token`

2020-10-14 20:33 UTC, dragonmantank commented on src/Client.php
> +        return $this->client->sendRequest($request);
This is going to sound dumb, but keeping this separate helps a lot with debugging. There's a lot of times I have to dump out or inspect the response, so having it as a bespoke variable makes that easier.

2020-10-14 20:33 UTC, dragonmantank commented on src/Client.php
> +        if (!$this->factory->hasApi($name)) {
This should be `has`, which is PSR-11 compliant.

2020-10-14 20:33 UTC, dragonmantank commented on src/Client.php
> +        return $this->factory->getApi($name);
This should be `get`, which is PSR-11 compliant.

2020-10-14 20:33 UTC, dragonmantank commented on src/Client/APIResource.php
> +     * @param array $body
To help with visual debt, I would remove any docblocks where we have clear type hints. It's less maintenance.

2020-10-14 20:45 UTC, dragonmantank commented
To expand on my "visual debt" note:

Visual Debt is anything that adds a cognitive load on the developer. This can come in many different forms, especially extraneous comments or complex methods. The harder a developer has to think to understand a block of code, the worse the code is. Another side of this is as the user has to _read_ more to understand the code, the harder time a developer has understanding the code. 

A lot of this code is very hold, so there are areas where there aren't any docblocks or type hints, some areas where we have docblocks but no hints, and somewhere we have both, and some where we only have type hints. It's a weird archeological dig through the history of PHP and the things that were needed at the time.

With the addition of type hinting, we can clear out one layer of visual debt - `@param` and `@return` annotations. Traditionally they existed to help IDEs and developers know what type of data was expected, but PHP can now directly enforce that with type hints. By duplicating the information as both a type hint and an annotation, it's not only two places for maintainers to keep up-to-date, but it's also additional information for developers to check.

As a good rule of thumb, if we have type hints, we don't need `@param` or `@return`. 9 times out of 10 these work well, with the other times being arrays that we can clarify (https://psalm.dev/docs/annotating_code/type_syntax/array_types/) or where we need to add clarification on _why_ we take a data type. 

Docblocks and comments exist to provide clarity on the code, not just to simply document it exists. 

Docblocks for things like `@throws` are still good, we have no code-equivalent way of documenting that up to an IDE. 

I use the following rules:
- If the method name is clear, I don't need to document the idea behind the method
- If the parameter has a type hint, I don't need to document the parameter
- If the parameter takes a clear, concrete type, type hint over docblocking
- If the parameter takes multiple types, docblock those types and leave off the type hint
- If the return value is type hinted, I don't need to document the return type
- If the return value is a clear, concrete type, type hint over docblocking
- If the return value is ambiguous or mixed, docblock those types and leave off the type hint

2020-10-14 20:56 UTC, SoftCreatR commented on src/Client.php
> +        if (!$this->factory->hasApi($name)) {
Then, tests fail:

> Prophecy\Exception\Doubler\MethodNotFoundException : Method `Double\FactoryInterface\P4::has()` not found.

2020-10-14 21:00 UTC, SoftCreatR commented on src/Client.php
> +        return $this->factory->getApi($name);
Then, tests fail:

> Prophecy\Exception\Doubler\MethodNotFoundException : Method `Double\FactoryInterface\P4::get()` not found.

2020-10-14 21:12 UTC, SoftCreatR commented
While I understand most of your explanation, I do not fully agree with all points. At the end (v2.0+) you would only use doc blocks if you have something to explain and omit them in all other cases, which makes a Developer think, that every unannotated param and every unannotated return type just means `mixed`. Dunno, if that's really the expected behavior.

However, do you want me to remove all doc blocks, that only describe params and return values?

2020-10-14 21:53 UTC, dragonmantank commented
> which makes a Developer think, that every unannotated param and every unannotated return type just means `mixed`

Not quite. A developer has no idea if we provide _no_ documentation (annotations, type hints, or comments). We should provide the best and most appropriate information we can though, which for parameters and return values can be annotations _or_ type hints. There's no need for both.

## 1. Worst Case

```php
function sendSMS($to, $from, $message) {}
```

This would be the worst case for a function (or method). We're providing no direction on what those variables are or their data types. The developer could make a reasonable inference that `$to` and `$from` are telephone numbers, and that `$message` is a string message. But for `$to` and `$from` should they pass an integer, a string, or an object? It's not clear, so the developer will have to dig into the function to see what it expects. 

The developer also has no idea if that function returns anything without looking at the source code.

## 2. Better
```php
/**
 * @param string $to
 * @param string $from
 * @param string $message
 * @return array $response
 */
function sendSMS($to, $from, $message) {}
```

This is better. The developer knows that each of the parameters are strings, and that the return value is some sort of an array. 



## 3. Even Better
```php
function sendSMS(string $to, string $from, string $message): array {}
```
Like the previous version, this gives the developer a bunch of information about the function. This is better because not only does it provide the exact same information as the annotations, it's actually enforceable at the engine level. 

## 4. Best
```php
/**
 * @throws ThrottleException
 * @throws ResponseException
 * @return array{status: integer, messageCount: integer, messages: array{price: string, messageId: string}}
 */
function sendSMS(string $to, string $from, string $message): array {}
```

This is the best case. Not only are we letting the developer know what exceptions may happen, but we're also documenting the return array (if this was a string or bool or more basic scalar, we could leave this annotation off). They no longer need to dig into any other source code to figure out how to handle the response, and can wrap their code more appropriately. 

<hr/>

> However, do you want me to remove all doc blocks, that only describe params and return values?

If we already have type hints, the `@param` and `@return` annotations do nothing but duplicate information the developer (or tool) already has (except arrays because PHP dropped the ball on that one). 

So when it comes to refactoring, if we are at \#1, we should move to \#2 by providing basic annotations. This is the safest bet as it avoids any errors with strict typing or type handling. The code will continue to work like it always has, with the additional documentation. While I didn't document it above, using the annotations from \#2 and \#4 gives you the best documentation-only developer docs.

If we are already at \#2, we can move to \#3 or \#4. #3 alone will get us safer code, and #4 will provide additional documentation. 

So if no type hints and no annotations exist, we should add annotations. If type hints exist, only annotate what is needed.

2020-10-14 21:58 UTC, dragonmantank commented on src/Client/ClientAwareTrait.php
> +        throw new RuntimeException('Vonage\Client not set');
It was, blindness on my part :)

2020-10-14 22:40 UTC, SoftCreatR commented
@dragonmantank What about this?

https://github.com/Vonage/vonage-php-sdk-core/pull/257/commits/e9fc64e7631e022a60db69846b60fa6a0d0f1ca2

However, I'm not sure, why the test fails now :/

2020-10-14 23:24 UTC, SoftCreatR commented
@dragonmantank What do you think? Should I just close this PR and create a new one, based on v3.0.0? For some reason, I think that'd be more useful.

2020-10-14 23:26 UTC, dragonmantank commented
I'll take a look at the tests here in a bit. We can finish this PR out, I tried updating the current v3 branch and the rebrand really messed it up. So since this is BC compatible, we'll get this one going, and I'll redo v3.

2020-10-15 04:45 UTC, dragonmantank commented
```
1) Vonage\Test\Call\CollectionTest::testHydrateSetsDataAndClient
TypeError: Return value of Double\Vonage\Call\Call\P2::setClient() must be an instance of Vonage\Call\Call, null returned

/home/ctankersley/Projects/vonage/php/vonage-php-sdk-core/src/Call/Collection.php:69
/home/ctankersley/Projects/vonage/php/vonage-php-sdk-core/test/Call/CollectionTest.php:80
```

I'm not sure why that double thinks it should be returning a Call object, it may be an issue with newer versions of the mocking library. 

Looking at that test though, it's just a bad test overall. It's testing to make sure methods are called but not that the end result even looks correct. 

Just mark that test Incomplete:

```php
$this->markTestIncomplete('Rework this test to make sure hydrate fills correct values');
```

2020-10-15 04:51 UTC, dragonmantank commented
Overall the changes look cleaner as well, doing some spot checks.

2020-10-15 12:22 UTC, SoftCreatR commented
> Overall the changes look cleaner as well, doing some spot checks.

If you are fine with the latest changes on the doc blocks, I'll do them in all source files.

2020-10-15 12:50 UTC, dragonmantank commented
Go ahead!

2020-10-15 13:24 UTC, SoftCreatR commented
Removing all the doc blocks that I've added takes longer, than expected 🤣

2020-10-16 02:51 UTC, dragonmantank requested changes
Another round of changes!

We're getting there!

2020-10-16 02:51 UTC, dragonmantank commented on test/Voice/Webhook/FactoryTest.php
> +     * @throws Exception
These `@throws Exception` call outs for the tests are unnecessary. Users should never be invoking these tests in their code.

2020-10-16 02:51 UTC, dragonmantank commented on test/Voice/Webhook/FactoryTest.php
> +namespace Vonage\Test\Voice\Webhook;
I'd like to revert this. I know some frameworks prefer to keep tests in the same namespace, but I prefer keeping the test namespace completely separate from the core namespace. This helps avoid collisions where maybe we want a bespoke `Vonage\Test` namespace in the future, but makes it much more clear this is not user-invokable code.

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/AutoDetect.php
> -     * @param string $to
I would revert this, as the new annotations are less useful

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Binary.php
> +     * @param $to
I would revert these as well, since it's removing info

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Client.php
> -     * @param string|MessageInterface $idOrMessage
I would revert this as well, since it's removing info

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/EncodingDetector.php
> +            [
I would revert this, it's making the file unnecessarily long and it's not going to improve any readability. This list also will never change, so not super worried about needing to maintain the list.

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/EncodingDetector.php
> +        return static function ($char) {
Is there a reason this is being converted to a `static` function? It's just a callable, and doesn't hold any persistent data inside of itself.

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Message.php
> +        $response = $this->getResponseData();
I would put this (and other silencers around request/response data) silencer back in.

It's silenced to help reduce the amount of deprecation warnings that happen on things the user can't change. For example, iterating over the Message object has the potential to generate a ton of deprecation warnings not only for the messages, but has a side effect of the response/request data access also being deprecated and triggering their own warnings, and it causes a cascading effect.

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Response/Collection.php
> +        parent::__construct($data);
These need swapped around, as the parent constructor relies on `$this->expected` being populated.

The other alternative is to just set it as a class property, this code is old enough I don't know if there was a reason we didn't. Either way, that array needs populated before calling the parent.

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Response/Message.php
> -        $return = parent::__construct($data);
Erring on the side of caution, I'd revert all the logic in this constructor but keep any syntactical changes. The logic here is extremely suspect, but this entire namespace is going away in v3 and this logic isn't replicated.

While yes, a `__construct()` method called magically during object creation returns the object, the `__construct()` method is directly callable as well and _can_ return something. With how this is set up, I would rather keep the sketchy behavior in case someone is actively abusing that ability. 

https://3v4l.org/RQPPE

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Text.php
> -     * @param string $to
I would revert these so we get the types back

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Unicode.php
> -     * @param string $to
I would revert these so we get the types back

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Vcal.php
> -     * @param string $to
I would revert these so we get the types back

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Vcard.php
> -     * @param string $to
I would revert these so we get the types back

2020-10-16 02:51 UTC, dragonmantank commented on src/Message/Wap.php
> +     * @param $to
I would revert these so we get the types back

2020-10-16 22:26 UTC, SoftCreatR commented on src/Message/Response/Message.php
> -        $return = parent::__construct($data);
I know, that you COULD use a return value from a constructor. But tbh, that is highly uncommon and fairly not recommended. However, in v3, this should be avoided.

2020-10-16 22:42 UTC, SoftCreatR commented on src/Message/EncodingDetector.php
> +        return static function ($char) {
Better scoping; in some cases can improve performance.

2020-10-16 23:26 UTC, SoftCreatR commented on src/Client.php
> +            $entity = unserialize($entity, [Verification::class]);
> I think the second parameter has to use an allowed_classes key:

Either an array of class names that should be accepted, FALSE to accept no classes, or TRUE to accept all classes. If this option is defined and unserialize() encounters an object of a class that isn't to be accepted, then the object will be instantiated as __PHP_Incomplete_Class instead. Omitting this option is the same as defining it as TRUE: PHP will attempt to instantiate objects of any class.

2020-10-16 23:46 UTC, SoftCreatR commented on test/Voice/Webhook/FactoryTest.php
> +     * @throws Exception
While this is correct, I would just leave them there. They don't hurt and your IDE may thank you later :) And whenever you watch at your tests, you clearly know what's going on or what could happen in unforeseen cases.

2020-10-22 16:49 UTC, dragonmantank commented
Just FYI, haven't forgotten about this just got pulled into another project for a few days that needed a bunch of attention!

2020-10-22 17:00 UTC, SoftCreatR commented
That's fine. I had the chance to take a short break 😂

2020-10-28 23:24 UTC, SoftCreatR commented
@dragonmantank Is it correct, that you tagged the latest version as 2.5.0? Wouldn't 2.4.2 be more suitable?

2020-10-29 01:05 UTC, SoftCreatR commented
FYI: This SDK isn't compatible with PHP 8, because of `laminas/laminas-diactoros`.

2020-10-30 08:11 UTC, SoftCreatR commented on test/Voice/Webhook/FactoryTest.php
> +     * @throws Exception
Done 😄

2020-11-09 22:50 UTC, dragonmantank requested changes
Nearly done. Most are notes for me to check a few things, and I'm going to revert a bunch of test changes from `$this->` to `self::` to cut down on the size of the changeset. Both work and there is no official "correct" way so it will just shrink this down a bit. I'll handle that and push to the branch. 

Home stretch!

2020-11-09 22:50 UTC, dragonmantank commented on src/Voice/Filter/VoiceFilter.php
> +        $dateStart->setTimezone(new DateTimeZone('Z'));
Need to check this, as the immutable class shouldn't be editable.

2020-11-09 22:50 UTC, dragonmantank commented on src/Voice/Filter/VoiceFilter.php
> +        $dateEnd->setTimezone(new DateTimeZone('Z'));
Same with this

2020-11-09 22:50 UTC, dragonmantank commented on src/Voice/NCCO/Action/Connect.php
> +    public static function factory(EndpointInterface $endpoint): Connect
Even though it's not used, can't remove it without it being a breaking change. Need to put back.

2020-11-10 00:36 UTC, dragonmantank commented
@SoftCreatR Can you open the PR to allow push access to the branch? Should be a checkbox on the PR that you can toggle. 

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2020-11-10 01:38 UTC, SoftCreatR commented
> @SoftCreatR Can you open the PR to allow push access to the branch? Should be a checkbox on the PR that you can toggle.
> 
> https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Done 😃

2020-11-11 16:51 UTC, dragonmantank requested changes
Few more comments on things to revert and check, stopping here because Github is acting funny. 24 files left.

2020-11-11 16:51 UTC, dragonmantank commented on test/NetworkTest.php
> +        $this->assertEquals('12345', $network['network_code']);
NOTE - Array access should throw a deprecation warning, need to check the underlying class

2020-11-11 16:51 UTC, dragonmantank commented on test/Numbers/ClientTest.php
> +        @$this->numberClient->purchase('1415550100', 'US');
Should support both ways of purchasing a number, so should have both tested.

2020-11-11 16:51 UTC, dragonmantank commented on test/Numbers/ClientTest.php
> +    // Then we get a POST request to cancel
Weird indentation here, needs reverted

2020-11-11 16:51 UTC, dragonmantank commented on test/Redact/ClientTest.php
> +            return $request instanceof RequestInterface;
Same as others, should revert because this check is always true.

2020-11-11 19:02 UTC, dragonmantank requested changes
The elephpant has been eaten.

Now going through all the notes I left and a final pass!

2020-11-11 23:08 UTC, dragonmantank requested changes
This is provisionally approved! Running through a few more things before I hit the approve button

2020-11-16 20:16 UTC, SoftCreatR commented
Well, I'm a bit confused. What needs to be done now?

2020-11-17 02:32 UTC, merged

2020-11-17 02:35 UTC, SoftCreatR commented
Okaaaaaaaay.... 😄

2020-11-17 02:37 UTC, dragonmantank commented
> Well, I'm a bit confused. What needs to be done now?

Nothing! Just a bit of cleanup before the merge. I've got one more PR that will get added to master before this goes out as an official release, but THANK YOU very much for the work!

2020-11-17 02:39 UTC, SoftCreatR commented
> > Well, I'm a bit confused. What needs to be done now?
> 
> Nothing! Just a bit of cleanup before the merge. I've got one more PR that will get added to master before this goes out as an official release, but THANK YOU very much for the work!

Well, it was fun while it lasted. Let's see, if there's something for me to do in v3 :octocat: