Feature/messages v1 ga
Vonage/vonage-php-sdk-core pull request #319
Opened 2022-06-06 08:44 UTC by SecondeJK

This PR adds the Messages API to the Client, as it has now moved from Beta to General Availability.

## Description

## Motivation and Context

## How Has This Been Tested?

## Example Output or Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-06 13:09 UTC, dragonmantank requested changes

2022-06-06 13:09 UTC, dragonmantank commented on src/Messages/ClientFactory.php
> +            ->setErrorsOn200(true)
Shouldn't this be false? The API docs say that it returns proper 4xx errors

2022-06-06 13:09 UTC, dragonmantank commented on test/Messages/ClientTest.php
> +<?php
Should add a test failure case, as well as a throttling case

2022-06-07 08:59 UTC, SecondeJK commented on src/Messages/ClientFactory.php
> +            ->setErrorsOn200(true)
This is true, PLUS when during integration testing I realised it might be, er, a good idea to use the correct base URI

2022-06-07 10:03 UTC, SMadani reviewed
A reasonable approach and implementation. Could reduce the `toArray` duplication and perhaps perform some validation, but this could be reasonably argued to be beyond the scope of the SDK (at this time anyway)

2022-06-07 10:39 UTC, SecondeJK commented on README.md
> +authentication can be either a JSON Web Token (JWT) or Basic Authentication. Read [this documentation] for how to set
I've not finished the docs yet, so yep there are some missing links

2022-06-07 10:40 UTC, SecondeJK commented on src/Messages/MessageTraits/TextTrait.php
> +trait TextTrait
Traits are PHP specific way of doing composition over inheritance.
Here's some info on it: 
https://www.php.net/manual/en/language.oop5.traits.php

2022-06-07 10:43 UTC, SecondeJK commented on src/Messages/MessageType/WhatsApp/WhatsAppCustom.php
> +    protected array $custom;
Arrays are everything in PHP (and in that respect, much misused), so we don't have a scalar Map type

2022-06-07 10:45 UTC, SecondeJK commented on src/Messages/MessageType/MMS/MMSAudio.php
> +        return [
Actually this does probably make sense to refactor and then do an array merge

2022-06-07 15:13 UTC, SMadani commented
I'd also add that `ImageObject`, `VideoObject` etc. are duplications. In the Java SDK I have a single internal class to handle these, might be an idea to consider

2022-06-09 10:34 UTC, SecondeJK commented on src/Messages/MessageType/BaseMessage.php
> +    protected string $clientRef = '';
Yeah my tests were duff for this actually. I've changed it to conditionally render instead.

2022-06-09 10:35 UTC, SecondeJK commented on src/Messages/MessageType/Viber/ViberText.php
> +        if ($this->requiresViberServiceObject()) {
The method itself sits in the trait, but the condition on it will need to live in the parent class

2022-06-09 10:37 UTC, SecondeJK commented
> I'd also add that `ImageObject`, `VideoObject` etc. are duplications. In the Java SDK I have a single internal class to handle these, might be an idea to consider

I think the naming is important from the developers' perspective here: rather than a "generic object", even though properties are often shared it at least tells the developer -what- they're actually sending or what is required

2022-06-09 11:28 UTC, SMadani commented
> > I'd also add that `ImageObject`, `VideoObject` etc. are duplications. In the Java SDK I have a single internal class to handle these, might be an idea to consider
> 
> I think the naming is important from the developers' perspective here: rather than a "generic object", even though properties are often shared it at least tells the developer -what- they're actually sending or what is required

I agree, but it could also be internalised where you have the URL and caption in the specific class as parameters and under the hood it constructs an object to wrap it. That said in this case I think your approach makes sense; the duplication is coincidental and preferring this to coupling is a sensible idea.

2022-06-09 11:44 UTC, SecondeJK commented on src/SMS/ClientFactory.php
> +            ->setCollectionName('sms')
Need to look at this, it -should- be a breaking change, but the tests are OK :|

2022-06-09 14:48 UTC, dragonmantank commented on src/Messages/MessageType/Messenger/MessengerAudio.php
> +    protected string $subType = BaseMessage::MESSAGES_SUBTYPE_AUDIO;
@SecondeJK has the final say, but the SDK is primarily built around letting users extend the classes when necessary. PHP does support `final` but I've always been a big proponent against it in libraries.

2022-06-10 10:07 UTC, SecondeJK commented on src/Messages/MessageType/Messenger/MessengerAudio.php
> +    protected string $subType = BaseMessage::MESSAGES_SUBTYPE_AUDIO;
I'd have to agree with @dragonmantank here: we don't use `final` -that- much in PHP, at least not in this sort of context.
`final` is mainly used within well-used, low-level code libraries, PHP core and structures where there tends to be a ton of tech debt/deprecations that need phasing out. It's used very much to mean FINAL in a sense that this is the last resort to stop extending.

2022-06-13 10:45 UTC, SMadani approved these changes

2022-06-13 12:50 UTC, dragonmantank requested changes
Overall everything looks OK.

What do you think about moving the types to a  "Channel" namespace instead of "MesageType"? That will follow the naming we use in docs for the individual services.

2022-06-13 12:50 UTC, dragonmantank commented on src/Messages/ClientFactory.php
> +            ->setBaseUrl($api->getClient()->getApiUrl() . '/v1')
You could actually set this to `/v1/messages` and save some configuration in the client.

2022-06-13 12:50 UTC, dragonmantank commented on src/Messages/ExceptionErrorHandler.php
> +class ExceptionErrorHandler
Does this need a custom error handler or can it just use the stock `APIExceptionHandler`?

2022-06-13 15:33 UTC, SecondeJK commented on src/Messages/ExceptionErrorHandler.php
> +class ExceptionErrorHandler
I gave it a custom handler because I expected more fields to come back from the API in the future - especially custom throttle rules or channel-specific errors in the future

2022-06-15 13:55 UTC, SecondeJK commented
> Overall everything looks OK.
> 
> What do you think about moving the types to a "Channel" namespace instead of "MesageType"? That will follow the naming we use in docs for the individual services.

This makes sense to me, and is done

2022-06-15 14:37 UTC, dragonmantank requested changes
Just a couple of docs updates

2022-06-15 14:37 UTC, dragonmantank commented on README.md
> +all the sendable message types under the namespace `\Vonage\Messages\MessageType`. The reason each type is separated
```suggestion
all the sendable message types under the namespace `\Vonage\Messages\Channel`. The reason each type is separated
```

2022-06-15 14:37 UTC, dragonmantank commented on README.md
> +Some `MessageType` objects require more arguments in order to be created. You can see the rough mapping of these
```suggestion
Some `Channel` objects require more arguments in order to be created. You can see the rough mapping of these
```

2022-06-15 14:41 UTC, dragonmantank approved these changes
LGTM!

2022-06-15 14:42 UTC, merged