remove outdated docs
Vonage/vonage-php-sdk-core pull request #331
Opened 2022-10-04 20:53 UTC by SecondeJK

This PR removes outdated docblock information.

## Description
The Talk NCCO no longer takes `voiceName`, which was deprecated some time ago. This removes it from the docblocks.

## Motivation and Context
Misleading docs causing confusion for developers: see #328 

## How Has This Been Tested?
No tests required.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-10-04 21:19 UTC, manchuck approved these changes

2022-10-04 21:19 UTC, manchuck approved these changes
:shipit:

2022-10-05 02:00 UTC, dragonmantank requested changes

2022-10-05 02:00 UTC, dragonmantank commented on src/Voice/NCCO/Action/Talk.php
> +     * @param array{text: string, bargeIn?: bool, level?: float, loop?: int} $data
Same as above, we can drop the redundant `@return` and `@param string $text`, and leave the array

2022-10-05 02:03 UTC, dragonmantank commented on src/Voice/NCCO/Action/Talk.php
> +     * @param array{text: string, bargeIn?: bool, level?: float, loop?: int} $data
Dropping `voiceName` is technically a breaking change. I know it's deprecated, but we should mark it as such and add `style`, `language`, and `premium` since the first two replaced `voiceName` and `premium` is now GA

2022-10-06 13:46 UTC, SecondeJK commented on src/Voice/NCCO/Action/Talk.php
> +    protected bool $bargeIn;
https://madewithlove.com/blog/software-engineering/typed-property-must-not-be-accessed-before-initialization/ this one

2022-10-19 14:18 UTC, dragonmantank approved these changes
Lgtm

2022-10-19 14:27 UTC, merged