Feature/meetings api beta
Vonage/vonage-php-sdk-core pull request #357
Opened 2023-01-27 12:38 UTC by SecondeJK

## Description

## Motivation and Context

## How Has This Been Tested?

## Example Output or Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-01-30 15:14 UTC, manchuck requested changes
I don't see any way to upload the image to S3.

2023-01-30 15:14 UTC, manchuck commented on src/Meetings/Client.php
> +        return $roomPayload;
```php
return array_map(
    function($room) {
        return $room
    },
    $response
);
```

2023-01-30 15:14 UTC, manchuck commented on src/Meetings/ClientFactory.php
> + */
See comment about file header

2023-01-30 15:14 UTC, manchuck commented on test/Meetings/ClientTest.php
> +            $this->assertEquals('https://api-eu.vonage.com/beta/meetings/rooms?page_index=1', $uriString);
I think you mean to have the query parameter be `page_size`. If not replace `page_index` with `start_id`. That is how it is in the API defines it

2023-01-30 15:14 UTC, manchuck commented on test/Meetings/ClientTest.php
> +            $this->assertEquals('https://api-eu.vonage.com/beta/meetings/themes/323867d7-8c4b-4dce-8c11-48f14425d888/rooms?start_id=245&end_id=765&page_index=1', $uriString);
`page_index` should be  `page_size` based on the context

2023-01-30 15:14 UTC, manchuck commented on test/Meetings/Fixtures/Responses/get-upload-urls-success.json
> +      "X-Amz-Signature": "abc123"
I would make these fields distinct to ensure that they are being passed correctly

2023-01-30 15:14 UTC, manchuck commented on test/Psr7AssertionTrait.php
> +use _PHPStan_582a9cb8b\Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator;
WTH ios PHPStan doing here?

2023-01-30 15:14 UTC, manchuck commented on test/Verify/ExceptionErrorHandlerTest.php
> +
See comment about file header here

2023-02-06 11:11 UTC, SecondeJK commented on src/Client/Exception/NotFound.php
> + */
I feel sorry for you when you have to re-review this and I've pulled them all out, but yeah we should bin it. There's no need for it, the license is included in the repo.

2023-02-06 11:16 UTC, SecondeJK commented on src/Client/Signature.php
> +         */
comment from 2016, useless

2023-02-06 11:17 UTC, SecondeJK commented on src/Meetings/Client.php
> +
We get pagination in, this becomes a lot nicer!

2023-02-06 11:19 UTC, SecondeJK commented on src/Meetings/Client.php
> +        return $roomPayload;
Not sure I'd agree with memory management, but can make the code look cleaner

2023-02-06 11:24 UTC, SecondeJK commented on test/Meetings/ClientTest.php
> +            $this->assertEquals('https://api-eu.vonage.com/beta/meetings/rooms?page_index=1', $uriString);
page_index is automatically added by the API Iteratorable class. For the time being, the backend will just ignore this query parameter and we might get defined pagination that will clean this up

2023-02-06 11:24 UTC, SecondeJK commented on test/Psr7AssertionTrait.php
> +use _PHPStan_582a9cb8b\Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator;
bad merge

2023-02-06 11:27 UTC, SecondeJK commented
@manchuck S3 now added, file headers cleaned up, not changed the `foreach` because `array_map` isn't used once in the codebase yet, and it would seem inconsistent here to just start using a different method of iteration when performance-wise there is no difference between the two from what I understand

2023-06-28 12:06 UTC, closed without merging

2023-06-28 12:06 UTC, SecondeJK commented
Will be replaced by new branch