Verify v2
Vonage/vonage-php-sdk-core pull request #389
Opened 2023-03-20 16:12 UTC by SecondeJK

## Description
Verify v2 has been made available for some time to developers. This PR adds the functionality to the SDK to use this API.

## Motivation and Context
Evolution of Vonage products and codebases

## How Has This Been Tested?
Full test suite has been added for the new client.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-03-21 14:25 UTC, manchuck commented on .gitattributes
> +/test/Verify2/Fixtures/Requests/* text eol=crlf
I would still recommend updating this to make all line endings crlf

2023-03-21 14:41 UTC, manchuck requested changes
I also got dinged for not allowing basic auth to verify v2. Is that something the PHP SDK allows already?

Aside from my other question about throwing the exception this is g2g

2023-03-21 14:41 UTC, manchuck commented on src/Verify2/VerifyObjects/VerifyEvent.php
> +        foreach (static::$mandatoryFields as $key) {
If the signature changes, it could be difficult to read the event from the webhook. Maybe not throw the exception?

If not, I would suggest having it be additive and list out all the missing keys instead of throwing if one key is missing  

(WDDT) What does @dragonmantank think?

2023-03-21 19:09 UTC, manchuck approved these changes

2023-03-22 12:52 UTC, SecondeJK commented on .gitattributes
> +/test/Verify2/Fixtures/Requests/* text eol=crlf
I think I'm leaning into being more explicit here, in case a general catchall breaks something else and is harder to find what the problem is

2023-03-23 09:41 UTC, SecondeJK commented on src/Verify2/VerifyObjects/VerifyEvent.php
> +        foreach (static::$mandatoryFields as $key) {
The options were to have magic methods or have something more explicit. I wanted to go for explicit, but you're right. As soon as the signature changes, all the getters and setters have to change.

2023-03-23 09:57 UTC, SecondeJK commented
I'm confused about Auth: this Client uses Basic Auth first before trying a Keypair

2023-03-23 10:07 UTC, merged