Subaccounts API
Vonage/vonage-php-sdk-core pull request #414
Opened 2023-06-14 11:08 UTC by SecondeJK

This feature adds the subaccounts API to the base Client.

## Description
See documentation changes in the README for usage.
You can now access the subaccounts API using `$client->subaccount()`

## Motivation and Context
Evolution of Vonage API/SDKs

## How Has This Been Tested?
Full unit test suite has been added. Run it:
`./vendor/bin/phpunit --testsuite subaccount`

Note: does not contain error handling from the API, as this is tested within the test class for `ApiResource`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-26 10:24 UTC, SMadani requested changes

2023-06-26 10:24 UTC, SMadani commented on src/Subaccount/Filter/Subaccount.php
> +    public ?string $startDate = null;
Start date is required. Either set the default here or in the client. Default can be the epoch.

2023-06-26 10:24 UTC, SMadani commented on src/Subaccount/Request/TransferRequest.php
> +        // TODO harden me with array key checks pls
Do TODO? Also reference is optional so if it's null it should be omitted.

2023-06-26 10:24 UTC, SMadani commented on src/Subaccount/Request/TransferRequest.php
> +    private string $amount;
Should be a decimal number.

2023-06-26 10:24 UTC, SMadani commented on src/Subaccount/SubaccountObjects/BalanceTransfer.php
> +            'balance_transfer_id' => $this->getBalanceTransferId(),
`balance_transfer_id` should be `id` (the spec is wrong).

2023-06-26 10:24 UTC, SMadani commented on src/Subaccount/SubaccountObjects/CreditTransfer.php
> +            'credit_transfer_id' => $this->getCreditTransferId(),
Don't know if the spec is correct since for balance transfers it's just `id` so in theory this is the same object as BalanceTransfer.

2023-06-26 10:24 UTC, SMadani commented on test/Subaccount/SubaccountObjects/AccountTest.php
> +        $this->assertEquals('2023-06-06', $instance->getCreatedAt());
Note that the format should be something like `2023-06-26T10:23:59Z`.

2023-06-26 17:56 UTC, dragonmantank requested changes

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Request/NumberTransferRequest.php
> +    public function __construct(string $apiKey)
Are `from`, `to`, `number`, and `country` not required to do the transfer? If they are all required they should come through the constructor to force the user to supply the information. Allowing a builder pattern here gives the user an opportunity to forget something.

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Request/TransferRequest.php
> +class TransferRequest implements ArrayHydrateInterface
Should rename this to `TransferCreditRequest` to be clearer

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Request/TransferRequest.php
> +    private string $amount;
For numerical safety because this is money, the user should pass in a string. We can cast it to a decimal later, but otherwise we're dealing with float issues.

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Request/TransferRequest.php
> +    public function __construct(protected string $apiKey)
If `to`, `from`, and `amount` are required (which makes sense) they should be moved to the constructor, not as builder options.

2023-06-26 17:56 UTC, dragonmantank commented on test/Subaccount/ClientTest.php
> +    public function testWillPatchSubaccount(): void
I know it's using a PATCH method, but from a "what are we doing" perspective we are updating the subaccount

```suggestion
    public function testWillUpdateSubaccount(): void
```

2023-06-26 17:56 UTC, dragonmantank commented on test/Subaccount/ClientTest.php
> +        $payload = [
Why are we using a raw array when we have an `Account` DTO?

2023-06-26 17:56 UTC, dragonmantank commented on test/Subaccount/ClientTest.php
> +        $payload = [
Why are we using a raw array instead of the `Account` DTO?

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Client.php
> +    public function createSubaccount(string $apiKey, array $payload): ?array
We should be using DTOs to force the user to submit the correct data. Arrays make it too easy for the user to forget something, or forces them to have the documentation handy.

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Client.php
> +    public function updateSubaccount(string $apiKey, string $subaccountApiKey, array $update): ?array
We should be using DTOs to force the user to submit the correct data. Arrays make it too easy for the user to forget something, or forces them to have the documentation handy.

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/ClientFactory.php
> +            ->setClient($this->vonageClient->reveal())
Is this a copy/paste error? This looks like a test mock but this isn't a test class.

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Hydrators/AccountHydrator.php
> +<?php
Why aren't you using the stock `ArrayHydrator`? You only need to have custom hydrators if are doing something special.

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Hydrators/BalanceTransferHydrator.php
> +class BalanceTransferHydrator implements HydratorInterface
Why aren't you using the stock `ArrayHydrator`? You only need to have custom hydrators if are doing something special.

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Hydrators/CreditTransferHydrator.php
> +<?php
Why aren't you using the stock `ArrayHydrator`? You only need to have custom hydrators if are doing something special.

2023-06-26 17:56 UTC, dragonmantank commented on test/Subaccount/ClientTest.php
> +        $payload = [
Marked the client method, but these things should be DTOs, not raw arrays. Alternatively, we should be requiring these values directly instead of hiding them in an array.

2023-06-26 17:56 UTC, dragonmantank commented on src/Subaccount/Filter/Subaccount.php
> +class Subaccount implements FilterInterface
This is namespaced properly, but should make this Hungarian since we do that in most places.
```suggestion
class SubaccountFilter implements FilterInterface
```

2023-06-28 08:54 UTC, SecondeJK commented on src/Subaccount/Request/TransferRequest.php
> +        // TODO harden me with array key checks pls
This was a tentative TODO which is why I left it in there. There's no need for them though, I'll ditch them

2023-06-28 08:56 UTC, SecondeJK commented on src/Subaccount/Request/TransferRequest.php
> +    private string $amount;
I actually missed the cast off, so that's a good spot. As tank says though, PHP can get awfully rough if you set it to a float initially

2023-06-28 09:01 UTC, SecondeJK commented on src/Subaccount/SubaccountObjects/CreditTransfer.php
> +            'credit_transfer_id' => $this->getCreditTransferId(),
I'd quite like to keep these objects separate as it's clear to the user, despite the fact that the API has muddied the waters when treating the two types of transaction the same

2023-06-28 09:47 UTC, SecondeJK commented on src/Subaccount/ClientFactory.php
> +            ->setClient($this->vonageClient->reveal())
aaah man

2023-06-28 11:36 UTC, SMadani approved these changes

2023-06-28 11:37 UTC, merged