Add Users Client
Vonage/vonage-php-sdk-core pull request #420
Opened 2023-07-24 21:12 UTC by SecondeJK

This PR adds the ability to CRUD users with a new Users client.

## Description
These endpoints have been moved from the Conversations API, into the Application API. It seems most logical to move them under their own Client namespace.

## How Has This Been Tested?
Tests have been created for this new client.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-07-24 21:32 UTC, dragonmantank requested changes

2023-07-24 21:32 UTC, dragonmantank commented on src/Application/Client.php
> +use Vonage\Users\User;
Can probably remove this since it's moved to it's own client

2023-07-24 21:32 UTC, dragonmantank commented on src/Application/Client.php
> +use Vonage\Entity\Filter\EmptyFilter;
Leftovers from before moving the users search to it's own client?

2023-07-24 21:32 UTC, dragonmantank commented on src/Application/Client.php
> +use Vonage\Entity\Filter\KeyValueFilter;
Leftovers from before moving the users search to it's own client?

2023-07-24 21:32 UTC, dragonmantank commented on phpunit.xml.dist
> +    </testsuite>
Should also add one for Users

2023-07-24 21:32 UTC, dragonmantank commented on src/Users/Client.php
> +        if (is_null($this->api)) {
`$this->api` is required, so we don't need these checks in new clients. That's a holdover from v2 and v3 where we allowed them to either be injected (the proper way) or built them for the user (in case they were using the clients directly)

2023-07-24 21:32 UTC, dragonmantank commented on src/Users/Client.php
> +    public function getUsers($pageSize = null, $order = null, $cursor = null): IterableAPICollection
Easier way is to create a custom filter for this with the page size, order, and cursor options. , then all you need to do is set it to `null` by default, and have then just make an `EmptyFilter` if the user doesn't pass anything in.

Also the name should be `listUsers` by convention.

2023-07-24 21:32 UTC, dragonmantank commented on src/Users/Client.php
> +        $userObject = new User();
You can cut down on the copy/paste by passing in a hydrator that is pre-set to the `User` class. Then you can just hydrate from there.

2023-07-24 21:32 UTC, dragonmantank commented on src/Users/ClientFactory.php
> +            ->setAuthHandler(new BasicHandler());
Users API uses a JWT, not Basic

2023-07-24 21:32 UTC, dragonmantank commented on src/Users/User.php
> +    public function __get($property)
Don't use magic methods as it makes it extremely hard for IDEs to automatically show intelesense info. While you could supplement this with an annotation, since we allow users to also use this object to make Users we should enforce proper getters/setters.

2023-07-24 21:32 UTC, dragonmantank commented on src/Verify2/VerifyObjects/VerifyEvent.php
> +use Vonage\Entity\Hydrator\ArrayHydrateInterface;
This should be split into a separate PR, this PR is about adding Users, not modifying Verify

2023-07-24 21:32 UTC, dragonmantank commented on src/Verify2/VerifyObjects/VerifyStatusUpdate.php
> +use Vonage\Entity\Hydrator\ArrayHydrateInterface;
This should be split into a separate PR, this PR is about adding Users, not modifying Verify

2023-07-24 21:32 UTC, dragonmantank commented on test/Application/ClientTest.php
> +use Vonage\Users\User;
Probably a leftover form before this was moved to it's own class?

2023-07-24 21:32 UTC, dragonmantank commented on test/Users/ClientTest.php
> +            new Client\Credentials\Container(new Client\Credentials\Basic('abc', 'def'))
Should be using JWT auth

2023-07-24 21:32 UTC, dragonmantank commented on src/Users/Client.php
> +    public function getUserById(string $id): User
This should just be `getUser()`, since it takes the ID. If this allowed other search params it could be `getUserBy[X]()`, but since we are passing the ID it should just be `getUser()`

2023-07-24 21:32 UTC, dragonmantank commented on src/Users/Client.php
> +    public function updateUser(User $user, string $id): User
Should not need to pass an `$id` for this, because the ID is part of the `User` object. Instead, we should throw an exception if `$user->id` is not set.

2023-07-24 21:32 UTC, dragonmantank commented on src/Users/Client.php
> +    public function deleteUserById(string $id): bool
Same as `getUserById()`, this should just be `deleteUser()` since it takes the ID.

2023-07-24 21:32 UTC, dragonmantank commented on test/Users/responses/delete-user-success.json
> +{}
This shouldn't exist as there is no response for deleting a user, just an empty body (`null`) and a 204 response

2023-07-24 21:32 UTC, dragonmantank commented on test/Users/ClientTest.php
> +        }))->willReturn($this->getResponse('delete-user-success', 204));
This should return a new Response with a `null` body and a 204, not a string body of `{}`

2023-07-25 13:22 UTC, dragonmantank requested changes
Just a couple of other ways to cut down on code

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/Client.php
> +    public function listUsers($pageSize = null, $order = null, $cursor = null): IterableAPICollection
```suggestion
    public function listUsers(FilterInterface $filter = null): IterableAPICollection
```

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/Client.php
> +        }
```suggestion
        if (is_null($filter)) {
            $filter = new EmptyFilter();
        } 
```

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/Client.php
> +use Vonage\Entity\IterableAPICollection;
```suggestion
use Vonage\Entity\IterableAPICollection;
use Vonage\Entity\Filter\FilterInterface;
```

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/Client.php
> +    public function listUsers($pageSize = null, $order = null, $cursor = null): IterableAPICollection
Just have the user pass in a filter directly

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/Client.php
> +        }
Then we can just make an empty filter if they don't pass anything at all

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/Hydrator.php
> +<?php
We can delete this and just use the `ArrayHydrator`, all the hydrators take a "prototype" class to know how what object to hydrate

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/ClientFactory.php
> +use Vonage\Client\Credentials\Handler\KeypairHandler;
```suggestion
use Vonage\Client\Credentials\Handler\KeypairHandler;
use Vonage\Entity\Hydrator\ArrayHydrator;
```

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/ClientFactory.php
> +        return new Client($api, new Hydrator());
```suggestion
        $hydrator = (new ArrayHydrator())->setPrototype(new User());
        return new Client($api, $hydrator);
```

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/Client.php
> +        $returnUser->fromArray($response);
```suggestion
        return $this->hydrator->hydrate($response);
```

2023-07-25 13:22 UTC, dragonmantank commented on src/Users/ClientFactory.php
> +        return new Client($api, new Hydrator());
`ArrayHydrator` takes a class to use as a sample, so we can tell the generic hydrator how to work without needing a custom one.

2023-07-25 13:23 UTC, SecondeJK commented on src/Users/Client.php
> +        }
did all the work for the filter, didn't do the last bit!

2023-07-25 13:30 UTC, manchuck requested changes

2023-07-25 13:30 UTC, manchuck commented on src/Users/Filter/UserFilter.php
> +     */
Not needed. IDE's will pick this up

2023-07-25 13:36 UTC, SecondeJK commented on src/Users/Filter/UserFilter.php
> +     */
must have missed this. I tend to not use docblocks anymore unless unusual behaviour needs to be documented, because typehinting and return types handle all this

2023-07-25 13:40 UTC, SecondeJK commented on src/Users/User.php
> +        }
More unreadable for me tbh
I get what it's doing, but feels more magic

2023-07-25 14:00 UTC, manchuck approved these changes

2023-07-25 14:31 UTC, dragonmantank approved these changes
LGTM!

2023-07-25 15:28 UTC, merged